services:
  - type: web
    name: uniq-pro
    runtime: node
    plan: free

    buildCommand: npm install

    startCommand: npm start

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production

    autoDeploy: true
